# ----------------------------------
#          INSTALL & TEST
# ----------------------------------
install_requirements:
	@pip install -r requirements.txt

check_code:
	@flake8 scripts/* base_prj/*.py

black:
	@black scripts/* base_prj/*.py

test:
	@coverage run -m pytest tests/*.py
	@coverage report -m --omit="${VIRTUAL_ENV}/lib/python*"

ftest:
	@Write me

clean:
	@rm -f */version.txt
	@rm -f .coverage
	@rm -fr */__pycache__ */*.pyc __pycache__
	@rm -fr build dist
	@rm -fr base_prj-*.dist-info
	@rm -fr base_prj.egg-info

install:
	@pip install . -U

all: clean install test black check_code

count_lines:
	@find ./ -name '*.py' -exec  wc -l {} \; | sort -n| awk \
        '{printf "%4s %s\n", $$1, $$2}{s+=$$0}END{print s}'
	@echo ''
	@find ./scripts -name '*-*' -exec  wc -l {} \; | sort -n| awk \
		        '{printf "%4s %s\n", $$1, $$2}{s+=$$0}END{print s}'
	@echo ''
	@find ./tests -name '*.py' -exec  wc -l {} \; | sort -n| awk \
        '{printf "%4s %s\n", $$1, $$2}{s+=$$0}END{print s}'
	@echo ''

# ----------------------------------
#      UPLOAD PACKAGE TO PYPI
# ----------------------------------
PYPI_USERNAME=<AUTHOR>
build:
	@python setup.py sdist bdist_wheel

pypi_test:
	@twine upload -r testpypi dist/* -u $(PYPI_USERNAME)

pypi:
	@twine upload dist/* -u $(PYPI_USERNAME)

# -----------------------------------
# DOCKER / GCP
# -----------------------------------

GCP_PRJ_ID="wagon-sve-certif"
GCP_IMG="api"
GCR_MULTI_REGION="eu.gcr.io"
GCR_REGION="europe-west1"

DOCKER_IMG="${GCR_MULTI_REGION}/${GCP_PRJ_ID}/${GCP_IMG}"

docker_build:
	@docker build -t ${DOCKER_IMG} .

docker_run_local:
	@docker run -e PORT=8000 -p 8080:8000 ${DOCKER_IMG}
# end point : localhost:8080

docker_push:
	@docker push ${DOCKER_IMG}

gcr_deploy:
	@gcloud run deploy --image ${DOCKER_IMG} --platform managed --region ${GCR_REGION} --allow-unauthenticated --memory 1Gi
# https://api-yufzv3bpca-ew.a.run.app/
